source = [
    '../src/config.cc',
    '../src/process.cc',
    '../src/setting.cc',
    '../src/third_party/inih/ini.c',
    '../src/utils.cc',
    'test.cc',
]

library_list = ['gloox', 'gtest', 'pthread']

env = Environment()
env.Program(target='test-all', source=source, LIBS=library_list)
