.TH TYRION-NODE 8 "July 16, 2010"
.SH NAME
tyrion-node - Tyrion node
.SH SYNOPSIS
.PP
.B tyrion-node
-c config-file
[--debug]
.SH DESCRIPTION
.PP
This is a Tyrion node daemon which authenticates and runs Tyrion service
requests.
.SH OPTIONS
.TP
.B -c, --config-file
The configuration file which must have all the general and XMPP authentication
settings.
.TP
.B --debug
This sets the debug level to the most verbose and displays the logging
information to stderr.
.SH "AUTHOR"
.PP
Tyrion was written by Silas Sewell.
.SH "SEE ALSO"
tyrion(1)
